server:
   port: 30000

eureka:
   client:
      service-url:
         #设置与Eureka Server交互的地址，查询服务和注册服务都需要依赖这个地址。默认是http://localhost:7777/eureka ；多个地址可使用 , 分隔。
         defaultZone: http://localhost:7777/eureka/

spring:
   application:
      name: service-consumer

feign:
   hystrix:
      enabled: true
